### ISSUE TITLE
Misalignment of table in overview if label is empty

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dolos#1003]
![image](https://user-images.githubusercontent.com/56451049/211335569-bcdc1749-07a6-4edb-b721-81853cc9c532.png)
![image](https://user-images.githubusercontent.com/56451049/211335746-09b149c4-ad58-4f87-8193-2d8b2b1537ab.png)

**Comment by bmesuere** [comment]
This should be solved automatically when #889 gets fixed.
