### ISSUE TITLE
Folder/Subfolder Traversing & combining results

### ISSUE THREAD

**Issue by dhruvg20** [dodona-edu/dolos#1067]
Hi, 

I wanted to check how could I traverse source codes under multiple levels of subfolders, and also may be exclude paths/file names? 
I was actually working around above by squashing/flattening the folders, but sometimes the same name files were overwritten.

Can I combine 2 results generated by the 'run' command? Thought is to run the tool across 1000s of code files and not load a single run.

Please do share your inputs 🙏

Yours Sincerely,
Dhruv Gupta

**Comment by dhruvg20** [comment]
For Subfolders I was able to also use the `csv` logic given here: https://dolos.ugent.be/guide/running.html#adding-metadata

**Comment by rien** [comment]
Indeed, you can generate a CSV with all the files you want to analyse with another command (for example: `find`) or if you are on Unix, you could use globbing. For example: if I want to analyse only C source and header files in subdirectories, you can use `dolos **/*.{c,h}`


Regarding your second question about combining multiple reports: this is currently not possible but we're thinking about how we can implement this in the future (#732).

**Comment by erikmartinessanches** [comment]
> Indeed, you can generate a CSV with all the files you want to analyse with another command (for example: `find`) or if you are on Unix, you could use globbing. For example: if I want to analyse only C source and header files in subdirectories, you can use `dolos **/*.{c,h}`
> 
> Regarding your second question about combining multiple reports: this is currently not possible but we're thinking about how we can implement this in the future ([#732](https://github.com/dodona-edu/dolos/issues/732)).

Inside a directory containing submissions in subfolders, tried `dolos run -f web -l javascript **/*.{js,jsx,css}` I get 0% highest similarity...

**Comment by erikmartinessanches** [comment]
> For Subfolders I was able to also use the `csv` logic given here: https://dolos.ugent.be/guide/running.html#adding-metadata

How if I may ask? I ran into [this issue](https://github.com/dodona-edu/dolos/issues/1691).
