### ISSUE TITLE
Filtering out a label seems to impact submissions with other labels in graph or cluster view

### ISSUE THREAD

**Issue by WLamotte** [dodona-edu/dolos#1085]
We have a course with different student groups and some staff members. In order to leave out test submissions from staff when viewing the cluster graphs or lists, we turn off their label. In the anonymized screenshots attached to this issue, the green "fowl" label stands for the staff users.
In the first screenshot, two clusters are visible, both without any staff members. In the second screen shot, the staff label (fowl) is turned off, and the orange cluster disappears. Even when then going to the "view by clusters" visualization, this cluster disappears (and reappears when selecting "fowl" again).
Note that none of the participants have more than one label.
![label in cluster graph 1](https://user-images.githubusercontent.com/55182821/227951979-99818579-4577-42b9-9208-54845b972a5c.png)
![label in cluster graph 2](https://user-images.githubusercontent.com/55182821/227951983-85f16854-51db-4df7-bf6d-62434aa076d8.png)
![label in cluster list 1](https://user-images.githubusercontent.com/55182821/227951990-2b5da230-6ad2-4f44-a856-bec75556c1ff.png)
![label in cluster list 2](https://user-images.githubusercontent.com/55182821/227951991-64bf8996-bb54-410c-b8fe-73342d1e163f.png)

**Comment by rien** [comment]
This is indeed unexpected behavior and likely a bug in the clustering somewhere. I'll look into reproducing this issue to fix this. Thank you for reporting.
