### ISSUE TITLE
filter the comparison output

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dolos#11]
The output should be filtered in at least 3 ways:
- exclude matches with the file itself (at post-processor)
- matches with given boilerplate code (add a blacklist to `Comparison`)
- common hashes matching many files. These are probably common constructs. The threshold for this could be user-defined. (at post-processor or when comparing)

**Comment by ISteampowered** [comment]
There is another case that should be filtered: when fileA and fileB match, fileB will naturally also match with fileA. This second match should not be shown in the output.
