### ISSUE TITLE
Back arrow doesn't work (view by cluster, pairs and submission)

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dolos#1120]
https://user-images.githubusercontent.com/56451049/236201147-d2df07d4-3416-4879-abfa-b401abd2d322.mp4

https://user-images.githubusercontent.com/56451049/236201150-86df9f63-19fe-4c10-ab3f-d742c1886425.mp4

https://user-images.githubusercontent.com/56451049/236201153-de047668-4bcb-4b1f-aa13-78b117311f45.mp4

**Comment by rien** [comment]
Yes, this is indeed a bug. Thanks for notifying us!

There is a rewrite happening in #1111, so we can fix the bug there.
