### ISSUE TITLE
`Share this report` link doesn't work

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dolos#1129]
Probably related to https://github.com/dodona-edu/dolos/pull/1076.

![image](https://github.com/dodona-edu/dolos/assets/56451049/cdf08640-801d-4061-ba1f-3a690a74fcea)

**Comment by rien** [comment]
The share URL is indeed missing the `/server/` part after dolos.ugent.be

**Comment by rien** [comment]
Confirmed this is fixed now.
