### ISSUE TITLE
Distance between connected plagiarism graph nodes is too large for submissions with low similarities

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#1143]
Plagiarism graph is broken in version 2.2.2

![image](https://github.com/dodona-edu/dolos/assets/5736113/2680cfc4-1e3a-4166-b9ea-d1cb7649ab04)

No force direction happens on the nodes.

**Comment by rien** [comment]
The force direction is currently calculated based on the similarity value. If these values are relatively low within an dataset, the forces are not strong enough to pull the nodes closer.

I think the solution would be to make this force relative to the highest similarity, and that the lowest force exerted by nodes is still strong enough to pull the nodes somewhat closer.

**Comment by pdawyndt** [comment]
I don't think that rescaling the [min, max] similarity to the [0, 1] would be enough, as one pair of identical submissions will yield no effect again and only highlight that pair.

As we only connect the edges above the threshold visually, we could only take the edges that are drawn into account (and give all the other edges zero weight or ignore them). I also wonder if in that case we even need to take into account edges weights: maybe just a binary "connected / not connected" graph would already be an improvement (or only with a slight impact on mutual distance based on edges weights, but at least this should be larger than no edge at all).
