### ISSUE TITLE
Heavy load on larger cluster page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#1160]
In my browser (Google Chrome) this page with a larger cluster from the demo hangs:

https://dolos.ugent.be/demo/pyramidal-constants/exercise/#/submissions/192

**Comment by bmesuere** [comment]
I can reproduce this, even on smaller cluster pages. Loading the page is ok, but after a few seconds the CPU usage spikes to 100% without interacting with the page. The profiler shows blocking JS on the main thread, but it is hard to see what's going on in the compiled/minified version.
