### ISSUE TITLE
Max fingerprint percentage does not work

### ISSUE THREAD

**Issue by AndreyNikitin** [dodona-edu/dolos#1163]
Currently -M flag does not work.
If use any amount less than 100 of the flag report fails with error `Kgram hash not found`
Broken in commit 1db346e7ed7e286ae05ac28d5a9f352f42385633

**Comment by rien** [comment]
Thank you for reporting. Unfortunately, I am not able to reproduce the error, but I do notice that adding a maximum percentage has no effect so there is definitely something broken.

Can you try to see if you're able to reproduce the error with our [simple-dataset.zip](https://github.com/dodona-edu/dolos/raw/main/samples/javascript/simple-dataset.zip)?

Can you also show the output of `dolos --version` and which system you're on?

**Comment by AndreyNikitin** [comment]
For example, 
```
yarn dolos run  -l "char" -M 0.01 -f csv simple-dataset/info.csv -o 01/
```
result in 01 folder
```
yarn run dolos serve 01
```
You can see errors on looking at the `pairs` screen `http://localhost:3000/#/pairs/147`

**Comment by rien** [comment]
We have added experimental support for ignoring template code and frequent fingerprints in PR https://github.com/dodona-edu/dolos/pull/1524
