### ISSUE TITLE
Drop support for Haskell

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#121]
Unfortunately, the tree-sitter team [has mentioned](https://github.com/tree-sitter/tree-sitter-haskell/issues/27) that the Haskell tree-sitter grammar is too complex and they have plans to rewrite it. But in the mean time it's no longer supported.

The Haskell grammar is currently stopping us from migrating to tree-sitter 0.16, which will allow us to use Node 12 again. So I propose that we (temporarily) drop support for Haskell until we have a working tree-sitter plugin for it again.

**Comment by patrickt** [comment]
If you’re still interested, the Haskell grammar is in significantly better shape than it was.

**Comment by rien** [comment]
Great to hear, we will try it out. Thanks @patrickt for letting us know.

**Comment by rien** [comment]
@patrickt I've just taken a look and the package was last published on npm 3 years ago (https://www.npmjs.com/package/tree-sitter-haskell). Are there plans to make a new release soon?

**Comment by patrickt** [comment]
@rien Yeah, if you need it we can take care of that. We’re about to do an initiative to make tree-sitter itself version 1.0, which will involve us pushing new grammar packages IIRC. Depending on your setup, you may be able to vendor the repo for the time being.

**Comment by rien** [comment]
There is currently no urgent need for a release, and if needed we can indeed help ourselves. Good to know there is some movement!
