### ISSUE TITLE
Creating templates to ignore sections of code

### ISSUE THREAD

**Issue by shreykshah** [dodona-edu/dolos#1213]
Is it possible to mark certain lines as a template such that sections of code are ignored? For example, if I have handed students some starter code to work with and asked them to modify small sections, the software similarity will come back as extremely high. I am trying to ensure the starter code is ignored.

**Comment by shreykshah** [comment]
The `-m` or `-M` flags are not necessarily robust, where we have to guess what the best values for these flags would be given our template. Are there any plans for explicit template support?

**Comment by rien** [comment]
We have added experimental support for ignoring template code and frequent fingerprints in PR https://github.com/dodona-edu/dolos/pull/1524
