### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by iz-rtx** [dodona-edu/dolos#1215]
Here is the log file

[2023-10-04T09_32_02_564Z-debug-0.log](https://github.com/dodona-edu/dolos/files/12801775/2023-10-04T09_32_02_564Z-debug-0.log)

**Comment by rien** [comment]
Hi, it looks like you don't have the "Tools for Native Modules" installed, which are needed to install Dolos on Windows. Can you try re-installing Node (you can download the installer here: https://nodejs.org/en) and make sure you tick the box "Automatically install the necessary tools." on the "Tools for Native Modules" page of the installer.

Or, if you don't need any custom parsers, you can use Dolos Online: https://dolos.ugent.be/server/#/ (more info: https://dolos.ugent.be/guide/server.html).

**Comment by rien** [comment]
I'm closing this issue as the installation should still work on Windows. Feel free to add additional comments if you still encounter some problems.
