### ISSUE TITLE
Libraries should use semantic versioning

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#1280]
We're noticing more developers are using our library (`dolos-lib`) and with the new core library coming up (`dolos-core`) we should adhere to semantic versioning.

Up till now we've used the same version for all our packages, and we've only bumped our major version when Dolos had a drastic UI change. However, we've often made breaking changes to our library which should've been a major version bump. This makes it hard for dependents to integrate our libraries.

I propose we keep our current versioning scheme for our apps (CLI and Web UI), but switch to semantic versioning for the libraries. To signify this change, we can bump `dolos-lib` and `dolos-core` in our next release to `3.0.0`.

Future releases will always release a new version of our apps (CLI, Web UI or webserver), but the libraries might not change.

**Comment by TRISHAHALDER** [comment]
please assign me this issue.

**Comment by rien** [comment]
Hi @TRISHAHALDER, this issue mostly applies to how releases are made, so unfortunately there is no opportunity for others to contribute here. If you're looking for easy issues, take a look at #1211 or #1126.

**Comment by rien** [comment]
We have been implementing this lately, so this issue can be closed.
