### ISSUE TITLE
implement JSON and html formatters

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dolos#13]
Allow users to export the results as json or as html.

**Comment by ISteampowered** [comment]
What templating engine should be used for the html formatter?

**Comment by bmesuere** [comment]
Do we need one or do you have suggestions? We want to generate static html pages where all javascript (and possibly css) is included in the page itself so they can be viewed locally without setting up a webserver.

**Comment by bmesuere** [comment]
I would also generate the html based on the json output.

**Comment by ISteampowered** [comment]
I was thinking about using either [haml.js](https://github.com/tj/haml.js) or [Dust.js](http://www.dustjs.com/) as both are fast and fairly simple to use.

**Comment by ISteampowered** [comment]
I am also not sure how the html should be structured, do we do something like moss where we have a main page and then several smaller pages that include the comparison, or de we have one main page with all the information on?

**Comment by rien** [comment]
Fixed with #37.
