### ISSUE TITLE
Can't move to other page / move down to the list in Submission and Can't search

### ISSUE THREAD

**Issue by byonicku** [dodona-edu/dolos#1334]
I can't do any search, and move to any other page in local web client Submission page. I have no idea since version before 2.4.2 works well

![image](https://github.com/dodona-edu/dolos/assets/82759105/005460fe-644b-4adb-9a38-a7b03e921bfe)

**Comment by rien** [comment]
I can reproduce this and it seems the web UI in the webapp is affected as well.

Thanks for the report!
