### ISSUE TITLE
Could not connect to the API

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#1335]
Here's a sequence of steps that consistently leads to `Could not connect to the API` on my Windows 10 machine (Google Chrome):

- click the field "Upload a file (*.zip) before the file you want to upload has been created (file explorer window stays open)
- export submissions from Dodona in another browser tab/window and save on local disk
- select exported submissions in file explorer
- select the option "I accept the above conditions"
- click "Analyze"

![image](https://github.com/dodona-edu/dolos/assets/5736113/0065b191-bf5e-4c36-99b0-8a30ececa71a)

More generally, upon selecting a file, Dolos shows a warning as long as the file explorer is open and no file is selected

![image](https://github.com/dodona-edu/dolos/assets/5736113/a9fa1e16-f5e8-483e-9259-baf8a9226aae)

**Comment by rien** [comment]
I cannot reproduce this locally (not in development nor using the production webserver). Since it requires local file actions with the file explorer open, I think this might be a bug in Windows or Chrome.

Are any errors printed to the browser console? What can you see in the network requests tab?

**Comment by pdawyndt** [comment]
I consistently got this issue when I posted it on GitHub, but can't reproduce it neither this evening. Will close the issue, but in general got some hiccups with the server version of Dolos lately (always worked after retrying once or twice).
