### ISSUE TITLE
Problems with docker-compose

### ISSUE THREAD

**Issue by mikaelGusse** [dodona-edu/dolos#1386]
**Describe the bug**
Hello! I am trying to host the Dolos api server locally on my machine for testing but I am having some issues with docker-compose and I am not quite sure if these issues are due to a configuration fault with my machine or with Dolos itself so I am making this issue to try to resolve this. 

I am unable to run the api using docker-compose due to an error. Additionally the build fails using docker-compose unless i specify for it only to build the api. 

**To Reproduce**
- When trying to build all of the docker images using docker-compose in the /dolos/ folder the build fails on the web step with error "failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory". I noticed that there is indeed no Dockerfile in the /web/ directory, so that is probably the issue there.

- Additionally if I try to simply build the api by itself using _docker-compose build api_ it succeeds as expected but when I try to run it using _docker-compose up api_, I get the following error:

Attaching to api-1
api-1  | /usr/local/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14: [BUG] Segmentation fault at 0x0065ffffa87b06c0
api-1  | ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux]
api-1  |
api-1  | -- Control frame information -----------------------------------------------
.... And this error message continues for a while with lots of additional information ....

**Your environment (please complete the following information):**
 - OS: MacOS 14.3.1
 - Browser: firefox
 
Please run `dolos --version` and paste the result:
```console
[user@system:~]$ dolos --version
Dolos v2.5.0
Node v20.11.1
Tree-sitter ^0.20.6

[user@system:~]$ docker-compose --version
Docker Compose version v2.24.5-desktop.1
```

**Comment by rien** [comment]
Hello @mikaelGusse , it seems there is an issue with Ruby 3.3 on aarch64 (https://bugs.ruby-lang.org/issues/20085).

Can you try changing the image in `api/Dockerfile` to `ruby:3.2` to see if it works? You might also need to change the ruby version in the `Gemfile`.

**Comment by rien** [comment]
Can you try updating the database image by running `docker pull mariadb:latest`?

Apologies for the errors, it seems you are the first MacOS ARM user who is trying out or web server.

**Comment by mikaelGusse** [comment]
![image](https://github.com/dodona-edu/dolos/assets/159019283/1ea51673-0775-4c4e-bb33-ee090cde1157)

It appears that it is already the newest version

**Comment by rien** [comment]
I don't know why it is trying to use the utf8mb4_0900_ai_ci collation, as we use the utf8mb4_general_ci our schema.

I also noticed the Dockerfile for dolos-web is missing, so that will cause an issue as well. 

I can dig deeper into this issue later this week and keep you updated. Thanks for reporting the issue!

If you want to use Dolos in the mean time, you can use our public and free to use instance over at https://dolos.ugent.be/server or install the Dolos CLI (see dolos.ugent.be/docs).
