### ISSUE TITLE
dolos-web service in docker-compose runs on incorrect host and port

### ISSUE THREAD

**Issue by mikaelGusse** [dodona-edu/dolos#1459]
**Which component(s) is your question about?**

Dolos API

**What is your question?**

I am trying to use the Dolos API by locally hosting it on my machine using the docker compose configuration and I have succesfully been using it in this way for around a week but now I have found an issue that I am having trouble fixing. I now get the following error regarding the dolos-web app when doing docker-compose up. 
<img width="756" alt="image" src="https://github.com/dodona-edu/dolos/assets/159019283/df706963-6dd3-4f8e-9a78-c4c11d12cce9">

And this log has the following information
<img width="590" alt="image" src="https://github.com/dodona-edu/dolos/assets/159019283/cf40ae34-45b7-4ddd-afd7-8fb57758c500">

Thus far i have tried the following:
- Reinstalling docker
- Deleting all Dolos redated from my computer and recloning from git
- Installing a newer node version

Do you have any pointers on how to proceed?
Thank you in advance!

**Comment by rien** [comment]
Hi @mikaelGusse, it just so happens I bumped on this same issue yesterday - it seems to be a problem when launching the docker-compose.yml on Windows (on Linux and MacOS it seems to work just fine).

Somehow the `--host` and `--port` arguments disappear and they get ignored.

I'll dig a bit deeper in this issue today and hope to have a fix soon. I will keep you updated.

**Comment by mikaelGusse** [comment]
I am actually running this on Mac (ARM to be precise), but good to hear that it is being worked on. 👍

**Comment by rien** [comment]
Ah, that's news. Thanks for letting me know!

**Comment by rien** [comment]
This was indeed a problem also present in MacOS and Linux, caused by switching to `npm` in #1438

Thanks for your input, I could've lost a lot more time troubleshooting windows.

**Comment by rien** [comment]
Can you try the fix I've just pushed to main? It's as simple as adding a ` -- ` before the arguments in the web Dockerfile.

**Comment by mikaelGusse** [comment]
Looks like it is working now here as well. Thanks for the quick reponse!

**Comment by rien** [comment]
Glad I could help.
