### ISSUE TITLE
Problem with VITE_API_URL enviroment variable in docker-compose.yml

### ISSUE THREAD

**Issue by eloymg** [dodona-edu/dolos#1575]
**Describe the bug**

There is an environment variable named VITE_API_URL in the docker-compose.yml file under the web section, but this variable doesn't work as expected. The VITE_API_URL variable is also defined in the web Dockerfile, where it works correctly during the build time but not at runtime.

**To Reproduce**
   1- Change the VITE_API_URL in the docker-compose.yml file.
   2- Run docker-compose up.
   3- Submit a file and observe that the web application makes a request to http://localhost:3000, ignoring the environment variable.

**How I solved the problem**
To solve this problem, I modified the docker-compose.yml file to use the web Dockerfile and updated the VITE_API_URL variable in the Dockerfile.

**Your environment (please complete the following information):**
 - OS: Debian 12
 - Docker: 27.0.3, build 7d4bcd8

**Comment by rien** [comment]
Hi @eloymg, you're right. That environment variable in the docker-compose does indeed have no effect. I'll remove it and add a comment where to change the API URL if needed.

Thanks for bringing this up!
