### ISSUE TITLE
Web UI: Enhance analysis overview

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#231]
The overview should give the users a good impression for each _intersection_ if there is a possibility of plagiarism or not. There will possibly be a lot of entries in this overview so we should make it easy for users to save some progress.

Possible features:
- Mark intersections as "certain plagiarism", "suspicious" and "innocent" (better tag names are possible).
- Add notes to files or intersections.
- Filter on these intersections.
- **Extension:** Give a quick impression of which parts of the intersections are shared/unique (best modeled after the barcode chart of #230)

**Comment by pdawyndt** [comment]
- could the progress not be part of the "review status": unreviewed, certain plagiarism, suspicious and innocent (false positive)
- could the Dodona annotations be reused for adding notes to files?

**Comment by rien** [comment]
- Yes, the review status was indeed the kind of progress saving I was thinking of.
- I would create a small "notes" field instead of annotations on lines of code, so there is not much reusability there. In addition, Dolos uses the Vue framework, so I think there may be possibilities of reusing code from dolos-web if we decide to experiment with Vue in Dodona.
