### ISSUE TITLE
Change output format from dolos analysis

### ISSUE THREAD

**Issue by ISteampowered** [dodona-edu/dolos#261]
The current output format puts all the fragment data into the `intersections.csv` file, while this is fine for smaller files this can get quite big for more realistic examples. Putting all the fragment data into the csv file has a considerable effect on the web UI as it is forced to load in all the fragments in all at once. Putting the this data into separate files would help resolve these issues.

**Comment by rien** [comment]
The output format should also use the new names (#255) we decided upon.
