### ISSUE TITLE
Optimize compare-view rendering

### ISSUE THREAD

**Issue by ArneCJacobs** [dodona-edu/dolos#266]
For larger files the rendering of a compare-view can get quite slow, for example the on hover highlighting might take about a second. There are two ways to optimize this:
 - only highlight the lines that are currently visible instead of all the lines in the file
 - optimize the spans so that not each span individually has to be highlighted but instead a parent spans is used for highlighting.

When this is done the first options should be tested first to see if it solves the problem.

**Comment by rien** [comment]
This has been solved by replacing prism by monaco (#818 )
