### ISSUE TITLE
Hash whole tokens instead of individual characters of the AST

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#276]
We now take substrings (kmers) of the stringified abstract syntax tree. Since the length of tokens are very specific to each parser, this makes our default configuration less portable between different languages.

Solution: hash whole tokens at once. 

We use a rolling hash with a fixed amount of characters in it. Since tokens have a variable length we need to add some changes to the hashing. I propose taking the hashes of the whole tokens (possibly memoizing this hash) and using that hash number as input for the rolling hash.

This change will also require some changes in how we keep track of the matching AST Region.

**Comment by pdawyndt** [comment]
I believe this is indeed a much more standard tokenization approach: use token k-mers instead of character k-mers (of the token stream)
