### ISSUE TITLE
Run dolos

### ISSUE THREAD

**Issue by gersonvneto** [dodona-edu/dolos#449]
Hello, 
I'm trying to test out dolos but I'm not able to run it.

I used `npm install -g dolos` and it installed with 2 warnings

>   npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
>   npm WARN deprecated Faker@0.7.2: Please use the (lowercase) 'faker' package from now on.
>   
>   added 4 packages, and audited 5 packages in 3s
>   
>   2 high severity vulnerabilities
>   
>   Some issues need review, and may require choosing
>   a different dependency.
>   
>   Run `npm audit` for details.

But when I run go to the terminal and run dolos, I receive the following:
bash: dolos: command not found

**Comment by rien** [comment]
Hi @gersonvneto, [dolos](https://www.npmjs.com/package/dolos) is another package not associated with this project. This project is published on npm under the scoped name [@dodona/dolos](https://www.npmjs.com/package/@dodona/dolos), so you can install our tool using:
```
npm install -g @dodona/dolos
```

I see it is our fault, we mention the wrong package in the documentation. Thanks for creating the issue and notifying us!
