### ISSUE TITLE
Allow for plain text matching

### ISSUE THREAD

**Issue by ISteampowered** [dodona-edu/dolos#50]
Add a setting to the user can choose if they want to use the code tree or just the plain text of the code itself for matching.

**Comment by pdawyndt** [comment]
Would seem logical to do plain text matching if no programming language is given.

**Comment by bmesuere** [comment]
> Would seem logical to do plain text matching if no programming language is given.

I don't agree. A user could assume that we detect the language automatically or that it doesn't make a difference for the results. If we use plain text when no language is set, the user would get suboptimal results and potentially never know it. Returning an error message when no language is set is more explicit.

**Comment by rien** [comment]
This is solved by #301.
