### ISSUE TITLE
Align terminology with publication

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#547]
- k-mers > k-grams (compare view; can we replace k with the actual value used?)
- continuous overlap > longest fragment (list view, compare view)
- swap order of total overlap and longest fragment (list view, compare view)
- k-grams > shared fragments ("blocks" panel)
- summary > list view (left panel)
- similarity graph > graph view (left panel)

**Comment by rien** [comment]
k-grams > fingerprints

**Comment by pdawyndt** [comment]
Naming the two files as "left" and "right" in the list view does not seem to make a lot of sense.

**Comment by pdawyndt** [comment]
There’s a whole body of literature on [code cloning](https://www.sciencedirect.com/science/article/pii/S0167642309000367). The terminology would that is used there:

- source file (of file for short); also file pair
- fragment: part of a source file
- clone: high similar pair of fragments; results from cloning a fragment (code duplication, plagiarism, …)
  - clone pair (explicit coupling of two fragments)
  - clone class/group: coupling of thee or more fragments

**Comment by rien** [comment]
_List view_ and _Graph view_ don't feel like sensible names for views in a user interface.
I will rename _Summary_ to  _Pair list_, and _Plagiarism graph_ to _Similarity graph_.

**Comment by pdawyndt** [comment]
Waarom niet “file pairs” en “plagiarism graph”?

**Comment by rien** [comment]
This was fixed in #564
