### ISSUE TITLE
Upload and display metadata on source files

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#549]
Allow users to provide additional metadata on the source files (in the CSV file) and display that information in the browser interface:

- [x] compare view: in the side-by-side view (e.g. interesting to see submission timestamps)
- [x] list view: as additional columns in the table
- [x] graph view: in a popup menu that appears when clicking or hovering over a node in the graph

There might also be metadata on file pairs (#552).

**Comment by maartenvn** [comment]
This is implemented.
