### ISSUE TITLE
Separate running a similarity analysis from inspecting its results graphically

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#554]
Running a similarity analysis and inspecting its results in the browser are now bundled as one command. Decoupling would allow to run an analysis once, but inspect the result multiple times. One way to decouple is by introducing two subcommands. Having an option to open a browser window after the analysis has finished still makes sense after decoupling.

**Comment by pdawyndt** [comment]
With “dolos compare” we might only run a pairwise analysis (and show the result in the compare view).

**Comment by rien** [comment]
This has been solved by #621
