### ISSUE TITLE
Some shared fragments look very dissimilar in compare view

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#561]
When selecting shared fragments, they sometimes look so dissimilar that it is hard to believe they result from the same fingerprints:

- quite different in length where they are expected to have the same length
- quite different in code structure where they are expected to have the same structure

We should check again if the aggregation / visualisation of shared fragments is correct.

**Comment by rien** [comment]
If you encounter this phenomenon in the future, linking screenshots or the actual files help in discovering the cause of this issue.

**Comment by rien** [comment]
Closing this issue as there is no way to reproduce. Please reopen if another case has been found.
