### ISSUE TITLE
Report all file pairs

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#563]
Currently the report only includes all file pairs with at least one shared kgram, we may want to include file pairs without shared kgrams to be complete.

**Comment by pdawyndt** [comment]
Another option is to provide a file listing, allow to select two files from that listing and show the compare view for the two selected files. This might allow to see the compare view for any pair of files, without having to include all pairs in the list view.

**Comment by rien** [comment]
We now provide a file listing (#861).
