### ISSUE TITLE
Submission overview and detail page

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#568]
Improve the current "file analysis page", by splitting it up into two parts:
- An overview page, where all submissions are listed with options to sort and search, and useful metrics to discover suspicious submissions.
- A submission detail page, where the information of one submission is present:
  - Submission metadata (hand-in time, label, code preview, ...) 
  - All matching submissions, with an easy way to compare with others
  - A clear link (or visualizations) to the cluster
 
In addition, there should be links to the detail page on the compare view to quickly navigate between submissions.

**Comment by maartenvn** [comment]
Closed by #861
