### ISSUE TITLE
Upgrade to vue-cli 5

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#575]
Sass-loader has dropped support for webpack 4, which is currently used by vue-cli 4. See: https://github.com/vuejs/vue-loader/issues/1831

Once vue-cli 5 is [out of beta](https://github.com/vuejs/vue-cli/releases), we can [migrate](https://next.cli.vuejs.org/migrations/migrate-from-v4.html#upgrade-all-plugins-at-once) and update sass-loader.

**Comment by nimpossible** [comment]
Not working still.
Issue created: https://github.com/vuejs/vue-loader/issues/1906

**Comment by maartenvn** [comment]
Closing this as the migration to Vue CLI 5 has been completed.
