### ISSUE TITLE
Writing fragments in CSV directory is slow and creates too many files

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#585]
We write currently write for each file pair a list of fragments in the `fragments/` directory of a CSV report. Because the amount of file pairs is quadratic related to the amount of files, this can result in the creation of thousands of very small files which. This is very slow and can consume a lot of much disk space.   

The previous way we handled this (changed by #274) wrote all fragments to a single CSV file which was loaded directly in the user interface. Because this was having a significant performance impact on the user interface, we decided to switch to the current system.

We should implement a better way to load and store the fragment information. One solution I can think of is to store fragments per file (instead of per pair).

**Comment by pdawyndt** [comment]
I guess we only need the fragments in the compare view for a pair of files. Would it be an option to recompute them on-the-fly (given that the parameters of the analysis are available in the web component)?

**Comment by rien** [comment]
That is indeed an option, but would require the library to be in its own package so the ui and the cli can share the same code.

Another option is to aggregate fragment information into "buckets".
