### ISSUE TITLE
Unable to run dolos using docker

### ISSUE THREAD

**Issue by Tazeen77** [dodona-edu/dolos#696]
Found out the substitution of Linux command $(pwd) in Windows is "%cd%".

can you please help me with step-by-step commands as after substitution also it's not working?
docker run --init --network host -v "$PWD:/dolos" \
    ghcr.io/dodona-edu/dolos -l javascript -f web *.js

P.s. I am new to docker. I am failing to type above in a single command

**Comment by rien** [comment]
Hi @Tazeen77,

There is no enter in the command, so this would be the command you need to execute on Windows:
```
docker run --init --network host -v "%cd%:/dolos" ghcr.io/dodona-edu/dolos -l javascript -f web *.js
```

Note that this command is to analyze JavaScript files in the current directory. If the files you want to analyze are another programming language or in another directory, you will need to change that in the command.

If you are uncertain if your docker is working correctly, you can also run the following command to test docker:
```
docker run hello-world
```

Let us know if you run into more problems, we want to make Dolos as easy to use as possible.

**Comment by Tazeen77** [comment]
I am getting this error

**Comment by rien** [comment]
There is probably only one file in your current directory. You should replace the `*.js` with the path to the files you want to analyze, or run this command in the directory with the files.

For example, if you have downloaded the sample files [from the tutorial](https://dolos.ugent.be/guide/running.html#running-dolos) and extracted them in your `Downloads` folder, you should run the following command in your home directory:
```
docker run --init --network host -v "%cd%:/dolos" ghcr.io/dodona-edu/dolos -l javascript -f web Downloads\dolos-js-samples\*.js
```
Or, change the current directory of your command prompt to that folder, by opening the folder in your file explorer and right click > "open command prompt here". You can also use the `cd` command on to change your current directory.

If you are unsure where your files are located, you can use the `dir` command to list all the files in the current directory,

**Comment by Tazeen77** [comment]
I am trying to do this for java file and I have 4 java code on my desktop

```
docker run --init --network host -v "%cd%:/dolos" ghcr.io/dodona-edu/dolos -l java -f web C:\Users\tazeen\Desktop\*.java
[error] You only gave one file wich is not a '.csv.'-file.
```

**Comment by rien** [comment]
In that case, you can try this command:
```
docker run --init --network host -v "C:\Users\tazeem\Desktop:/dolos" ghcr.io/dodona-edu/dolos -l java -f web *.java
```

This will put the files on your desktop in the `/dolos/` folder inside the docker container, so `*.java` should expand to all the Java files located there.

If that you keep having the same error, you can try specifying the filenames directly instead of using `*.java`.

**Comment by Tazeen77** [comment]
I am getting same error. Tried both * and file name.
![image](https://user-images.githubusercontent.com/59621766/153021155-678568e5-75ef-48ab-8ad0-0a15cf2a206c.png)

**Comment by rien** [comment]
It seems you are trying to analyze only one file. This is something Dolos does not do: Dolos will search for similarities between two or more files. Dolos is not made to search for plagiarism with external sources (for example stackoverflow).

If you want to use Dolos, you need to pass more than one file.

**Comment by Tazeen77** [comment]
I understand that.
I did this but I am not getting anything on 3000

**Terminal output:**
```
docker run --init --network host -v "C:\Users\tazeen\Desktop:/dolos" ghcr.io/dodona-edu/dolos -l java -f web TargetSum.java AngelTriplet.java
Writing results to directory: dolos-report-20220209T084154012Z
Metadata written.
Pairs written.
kgrams written.
Files written.
Completed
Dolos is available on http://localhost:3000
Opening the web page in your browser...
Press Ctrl-C to exit.
```
![image](https://user-images.githubusercontent.com/59621766/153158486-4776ddd9-f059-4afc-a13d-f0ffd206e771.png)

Also how can I check for the entire folder?

**Comment by rien** [comment]
#### localhost:3000 not working
It seems like `--network host` is not working properly on Windows. You can omit this and try to reach the docker directly through the container IP address. You would need to add the `--host 0.0.0.0` argument to dolos (see below). 

You can discover the container IP with the following steps:
1. Find the container id using `docker ps`
2. Inspect container information with `docker inspect <container id>`
3. Look for the value of `IPAddress`

The UI should be available over at the IP address port 3000 (for example http://172.17.0.2:3000) 

#### Analyzing all files in the directory

The `*.java` part should expand to all files ending with `.java`, but doesn't seem to work in your command prompt. Can you try using powershell?

The full command (with the above fix) would be (in PowerShell):
```
docker run --init -v "C:\Users\tazeem\Desktop:/dolos" ghcr.io/dodona-edu/dolos --host 0.0.0.0 -l java -f web *.java
```

**Comment by jkatzenschlagerhtl** [comment]
Have the same issues as @Tazeen77 when trying *.js or *.java. Using explicit files, the check is working. 

But accessing the docker container with the browser is not working. I'm using docker desktop. Tried host and --host with the docker IP but don't get a response on localhost/container IP.

**Comment by rien** [comment]
I think `*.js` does not work because that is a feature of bash. You could try installing bash shell on windows to use this functionality. You can also create a csv-file with a row for each file you want to analyze if that is easier to use for you.

It's weird that docker does not seem to be working. Unfortunately I'm unable to troubleshoot those problems at the moment.

I do have good news however: we're building a webserver so you don't have to use docker or the command line anymore. We expect to make this server available soon.

**Comment by rien** [comment]
The documentation has been updated to mention that file globbing does not work on Windows. Please reopen or create a new issue if you encounter any more problems.
