### ISSUE TITLE
Unable to run "npm install -g @dodona/dolos"

### ISSUE THREAD

**Issue by Tazeen77** [dodona-edu/dolos#704]
Getting this:
![image](https://user-images.githubusercontent.com/59621766/154204196-c2d7d658-5625-4869-a2bc-558b5601f513.png)

**Comment by rien** [comment]
It looks like you don't have all dependencies of `node-gyp` installed can you perform the following steps ([mentioned on their installation page](https://github.com/nodejs/node-gyp#on-windows)):
- Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload) or [Visual Studio Community](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community) (using the "Desktop development with C++" workload)
- Launch cmd, npm config set msvs_version 2017

If you've completed these steps, you may need to reinstall some dependencies by executing
```
npm install -g --force @dodona/dolos
```
