### ISSUE TITLE
Unable to add another language using tree-sitter

### ISSUE THREAD

**Issue by berkeka** [dodona-edu/dolos#706]
I'm an undergrad student working on an assignment control web application as a university project that will be possibly used in our university. We want to use dolos for plagiarism checks.

I'm having some issues adding different programming languages that aren't included in the dolos package as a dependency like Ruby and Rust.

<img width="203" alt="Screen Shot 2022-02-15 at 18 30 02" src="https://user-images.githubusercontent.com/42390512/154766826-e62b9f44-fbbc-4eb6-838c-81508c3c71a6.png">

<img width="478" alt="Screen Shot 2022-02-15 at 18 29 50" src="https://user-images.githubusercontent.com/42390512/154766909-78aa3696-a943-44ea-bf97-769b54238487.png">

After installing both dolos and tree-sitter for another programming language running dolos fails for both Ruby and Rust.

<img width="1148" alt="Screen Shot 2022-02-15 at 18 30 28" src="https://user-images.githubusercontent.com/42390512/154767078-aa0d13a8-2f9d-436c-a643-67ec22a9656c.png">

No tokenizer found error is expected when the tree-sitter package cannot be found. Maybe there is an issue with the runtime detection of tree-sitter parsers or I might be missing something important.

Can you please help me out?

**Comment by bmesuere** [comment]
Thank you for reporting this issue. We have identified the cause and will release a fix later today.

**Comment by rien** [comment]
Version 1.5.1 with a fix is being released right now and should show up any moment on the npm package repository.

Thank you again for reporting the issue. Be sure to get in touch if you need some help or advice when using Dolos, we would love to hear how your project turns out!
