### ISSUE TITLE
Can't run 'serve' - no 'fragments' for python check

### ISSUE THREAD

**Issue by z2i** [dodona-edu/dolos#733]
Hello.

- I could run: dolos -f web -l python $FILES (passing needed python files in $FILES variable)
- Dolos writing results to corresponding folder:
      Writing results to directory: dolos-report-20220504T141534453Z
      Metadata written.
      Pairs written.
      kgrams written.
      Files written.
- There are following files in the report folder: files.csv, kgrams.csv, metadata.csv, pairs.csv
- I'm able to see results in a browser on localhost:3000.

- Now I'm trying to run 'dolos serve dolos-report-20220504T141534453Z' and getting the following error:
_[error] ENOENT: no such file or directory, access 'dolos-report-20220504T141534453Z/fragments'
[error] The given path 'dolos-report-20220504T141534453Z' does not seem like a Dolos report._

There is no fragments file or folder in dolos-report folder.

How can I run existing report?
Thank you in advance.

Dolos v1.5.1
Node v16.14.1
Tree-sitter v0.20.0

**Comment by rien** [comment]
I'll create a fix for this issue tomorrow.
