### ISSUE TITLE
Review formatting en linting in GitHub actions

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#768]
We currently have some formatting and linting rules, but our codebase does not adhere to them in some places.

- [x] Check our formatting in GitHub actions
- [x] Make sure warnings are only shown one time (it is now shown for each node version)
- [ ] Recommend using pre-commit hooks in the README
- [x] Review our linting rules

**Comment by maartenvn** [comment]
Closed by #783 and #866
