### ISSUE TITLE
Subtree matching algorithm

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#79]
PR #78 implements a subtree matching algorithm as an interesting alternative to hash matching. But we need to compare these two techniques to pick which one to use.

@ISteampowered it would be useful to have a link to a description of this algorithm.

**Comment by ISteampowered** [comment]
The algorithm that I implemented in #78 is based on the one described in the pdf below starting from page 15. [graph-00-01-c.pdf](https://github.com/dodona-edu/dolos/files/3809622/graph-00-01-c.pdf). I would supply a link the original page is down

**Comment by rien** [comment]
@yasminosb this is something you could potentially look into if you like.
