### ISSUE TITLE
tokenizer test sometimes fails with "Illegal invocation"

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#80]
```
 FAIL  src/lib/__tests__/tokenizer.test.ts
  ● Test suite failed to run

    TypeError: Illegal invocation



      at Object.get [as rootNode] (node_modules/tree-sitter/index.js:20:35)
      at Object.<anonymous> (node_modules/tree-sitter/index.js:16:26)
      at Object.<anonymous> (src/lib/codeTokenizer.ts:740:40)
```

**Comment by bmesuere** [comment]
Same here: https://github.com/dodona-edu/dolos/runs/276708215

I already deconstructed the test in question, and simply including treesitter causes the issue 😞

**Comment by rien** [comment]
I currently use this command to perform tests:
```
find src/lib/__tests__/ -maxdepth 1 -type "f" | xargs -n1 node node_modules/jest/bin/jest.js
```
It's slower, but at least we can perform all the tests.

**Comment by rien** [comment]
I've reported this bug with https://github.com/tree-sitter/node-tree-sitter/issues/53 and https://github.com/facebook/jest/issues/9206. It seems to be cause by Jest initializing a library multiple times in the same VM, which breaks the native code wrapping.

A solution would be to bind the module importing this library to a global variable, but since we're using TypeScript, this would make our code very messy.

I'll rewrite the tests in [ava](https://github.com/avajs/ava) which also supports snapshots and parallel testing.
