### ISSUE TITLE
No graph hull in cluster view when cut-off is 100%

### ISSUE THREAD

**Issue by maartenvn** [dodona-edu/dolos#848]
No graph hull in cluster view when cut-off is 100%

![image](https://user-images.githubusercontent.com/6013068/185352109-a32abda6-a35d-49b7-86d2-d06e47492fd4.png)

**Comment by maartenvn** [comment]
This is not a bug.

**Comment by pdawyndt** [comment]
Can you explain why this is not a bug, e.g., why there's a deliberate choice here not to show a background for the clusters?

**Comment by maartenvn** [comment]
This wasn't an issue in my current dataset as there weren't any similarities above 99%. I was able to reproduce this again on a different dataset.

Re-opening this, as it is indeed a bug 😅

**Comment by maartenvn** [comment]
Fixed in #879
