### ISSUE TITLE
Cleanup D3 components

### ISSUE THREAD

**Issue by maartenvn** [dodona-edu/dolos#876]
- [x]  Merge similarity histogram on homepage with the similarity/longest fragments histogram on the submission page
- [x] Rename components to more suitable names
- [x] Remove `d3-tools` directory and move components into the general `components` directory
- [x] Make all D3 components re-scalable when the width changes

**Comment by rien** [comment]
The heatmap slows down when a lot of submissions are rendered. Because it is not very readable for lots of submissions, it would be better to hide it when more than 50 submissions are shown.
