### ISSUE TITLE
Not all submissions show up in overview submission table

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#890]
Submission table on overview page:
![image](https://user-images.githubusercontent.com/3226995/188478967-76f01815-3310-498e-a179-4830610ab0c8.png)

Submissions page:
![image](https://user-images.githubusercontent.com/3226995/188479021-c4d4884d-84d7-4d43-bd2f-31f62bcfa0f8.png)

**Comment by rien** [comment]
This probably uses the "interestingness" metric, but since it is not shown, it is probably best to just use similarity here.

**Comment by maartenvn** [comment]
This appears to be a bug. The files are sorted by similarity on the overview page and the first 10 are sliced for display, so something else is wrong here.
