### ISSUE TITLE
Web UI does not work with unkown languages

### ISSUE THREAD

**Issue by rien** [dodona-edu/dolos#957]
For example: when installing `tree-sitter-php`: the analysis runs fine in the CLI, but the Web UI errors with the notice `Error: The module 'tree-sitter-php' could not be found. Try to install it using npm or yarn, but it may not be supported (yet).`

The Web UI should never try to load `tree-sitter` libraries, since they a native component.

This seems to be introduced with version v2.0.1

**Comment by SgtBlade** [comment]
Any update on this so far? I'm experiencing the same for CSS & HTML

**Comment by rien** [comment]
The quickest way to fix this issue is to temporarily downgrade to Dolos v2.0.0

I will be able to make a fix in a few weeks, but there are currently some end-of-the-year tasks requiring my attention.

**Comment by SgtBlade** [comment]
Allright that's what I've done for now. I've looked into fixing it myself but there are so many commits and I don't know where to start looking for it. If you think you know where the issue may lie more or less, feel free to let me know and I'll look further into it.

On a side note, I'm coming from version 1.3 and I really like the new UI but was the option to filter on fragment length removed?

**Comment by rien** [comment]
I know what causes the issue, but I'm not completely sure as to what the fix might be.

Some context:

This bug was introduced by https://github.com/dodona-edu/dolos/pull/931 which cleans up how we select the language (and the correct `tree-sitter` parser).

This bug is caused by the web UI trying to load `tree-sitter-php` in a web environment, however since the tree-sitter grammars require native extensions, this cannot work. We "fix" this by not loading parsers or classes importing these parsers with Webpack: https://github.com/dodona-edu/dolos/blob/ff3f704f83f69a9687e5ad50feba8f555d199da4/web/vue.config.js#L28-L34

We also only conditionally `require` the parsers and classes needing the parser in `dolos-lib` when needed:
https://github.com/dodona-edu/dolos/blob/ff3f704f83f69a9687e5ad50feba8f555d199da4/lib/src/lib/util/language.ts#L35-L54

The PR introducing this bug rewrote that code and the web UI currently still tries to `require` a parser if the language is not know. If you could figure out why, and prevent it from doing so (the web UI should never need this parser), then this issue will be fixed.

> On a side note, I'm coming from version 1.3 and I really like the new UI but was the option to filter on fragment length removed?

Unfortunately yes, we could not find a way to fit this in the new UI (and we did not think this feature was popular). If you want, we can add it again? However, you can also use the  `--min-gragment-length <l>` (short: `-s <l>`) CLI option to ignore fragments smaller than `l`.

**Comment by SgtBlade** [comment]
> The PR introducing this bug rewrote that code and the web UI currently still tries to require a parser if the language is not know. If you could figure out why, and prevent it from doing so (the web UI should never need this parser), then this issue will be fixed.

I'll look into this and post an update if I manage to fix it. 

> Unfortunately yes, we could not find a way to fit this in the new UI (and we did not think this feature was popular). If you want, we can add it again? However, you can also use the --min-gragment-length <l> (short: -s <l>) CLI option to ignore fragments smaller than l

I'll try using the CLI method then. I find it quite useful when using it to check CSS. Chances are high that there are a lot of similarities in CSS within the same assignment, by setting the fragment length to >10 I was able to more accurately spot the plagiarisms.

**Comment by rien** [comment]
@SgtBlade @tsieger I've just made a new release with a proper fix for this issue, you can try it by installing [Dolos v2.0.2](https://github.com/dodona-edu/dolos/releases/tag/v2.0.2)

**Comment by SgtBlade** [comment]
Sorry for the late reply. I've tested the new version and everything seems to be working very well. Many thanks for the update!
