### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dolos#974]
A priority for the next release will be improving the performance. This issue aims to track the efforts.

Frontend
- Side by side sometimes doesn't load
- Clustering is slow 
  - [x] #862
  - [x] #908
  - [ ] #930 (postponed)
- Can we use sqlite/duckdb client side to speed things up?

Backend
- Out of memory errors
  - [x] Profile to determine root cause #1011
- Maximum call stack size
  - [x] Profile to determine root cause #1011

**Comment by rien** [comment]
For reports with a lot of very similar files, the similarity threshold detection will sometimes suggest a very low threshold. While calculating the clusters is fast enough, it is rendering the graph itself that is slowing things down a lot in those cases.

**Comment by rien** [comment]
Closing this, as performance is much better now since #1079 and #1011
