### ISSUE TITLE
--fragment-sort-by not working?

### ISSUE THREAD

**Issue by tsieger** [dodona-edu/dolos#976]
It seems that the command line option `--fragment-sort-by` does not affect the order of matching fragments shown in the console.
E.g., `dolos run -l cpp -s 8  --fragment-sort-by "kgrams descending"` gives the same order of fragments as `dolos run -l cpp -s 8  --fragment-sort-by "kgrams asscending"`, where the fragment with the maximal number of matching k-grams appears in the middle of the output.

**Comment by rien** [comment]
Indeed, this does not seem to work, thanks for noticing!
